[package]
name = "ripple"
version = "0.2.0"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"
license = "MIT"
keywords = ["statistics", "probability", "inference"]
categories = ["science"]
build = "build.rs"
publish = ["crates-io"]
readme = "README.md"
description = "General-purpose DSP data structures and algorithms"

[dependencies]
